### ISSUE TITLE
[1.16.5] OpenGL error: 1282 on scans

### ISSUE THREAD

**Issue by estafeit** [MightyPirates/Scannable#104]
Hello. Whenever I try to scan for blocks I get an error 1282 popping in chat, while no boxes appears. Scanning for animals sort of work, the info dots are here, but i still have the error.

Initially i have this kind of log : 
```
[13Apr2022 21:55:14.314] [Render thread/ERROR] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_block, at: endBlockEntities
[13Apr2022 21:55:14.329] [Render thread/ERROR] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Depth formats do not match.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL30C.glBlitFramebuffer(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL30.glBlitFramebuffer(GL30.java:1861) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at li.cil.scannable.client.renderer.ScannerRenderer.updateDepthTexture(ScannerRenderer.java:113) ~[scannable:1.7.6]
	at li.cil.scannable.client.renderer.ScannerRenderer.render(ScannerRenderer.java:81) ~[scannable:1.7.6]
	at li.cil.scannable.client.renderer.ScannerRenderer.doRender(ScannerRenderer.java:67) ~[scannable:1.7.6]
	at li.cil.scannable.client.renderer.ScannerRenderer.render(ScannerRenderer.java:56) ~[scannable:1.7.6]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1862) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.29-launcher.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

When I disabled my shader, that changed to : 
```
[13Apr2022 22:19:11.604] [Thread-64/ERROR] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Depth formats do not match.)
java.lang.Exception: Stack trace
	at net.minecraft.client.renderer.GlDebugTextUtils.func_209244_a(GlDebugTextUtils.java:189) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
```

While disabling optifine changed it to a bunch of : 
```
[13Apr2022 22:31:06.723] [Thread-63/INFO] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL debug message, id=1282, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION error generated. Depth formats do not match.
```

In any case, I can't seem to see any block highlight.

I can tell your mod can work with my modpack (enigmatica 6 expert) and optifine enabled, as I saw it running perfectly on another computer. Might be hardware related (I run an old 980 Ti).

**Comment by estafeit** [comment]
It appears i didn't know how to  use the module. Now that I do it correctly, oultines are appearing. Still have the errors though.

**Comment by fnuecke** [comment]
Could you please test with just Scannable, see if it's happening then, too.

I can't repro this, but I'll try to make time to investigate how this may theoretically happen.

**Comment by MrChouSaru** [comment]
I'm also having issues with this. Sometimes it works perfectly but still provides the "OpenGL error 1282" and other times it detects nothing and gives the error. 

`[10:58:03] [main/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. Depth formats do not match.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL30C.glBlitFramebuffer(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL30.glBlitFramebuffer(GL30.java:1861) [lwjgl-opengl-3.2.2.jar:build 10]
	at li.cil.scannable.client.renderer.ScannerRenderer.updateDepthTexture(ScannerRenderer.java:113) [?:1.7.6]
	at li.cil.scannable.client.renderer.ScannerRenderer.render(ScannerRenderer.java:81) [?:1.7.6]
	at li.cil.scannable.client.renderer.ScannerRenderer.doRender(ScannerRenderer.java:67) [?:1.7.6]
	at li.cil.scannable.client.renderer.ScannerRenderer.render(ScannerRenderer.java:56) [?:1.7.6]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1862) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$498/921406983.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[10:58:03] [main/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_block (none), at: endBlockEntities
`
Running on a 3070ti,  drivers upto date, i've also backdated just incase to no avail 

This is running on Enigmatica 6 Expert pack using a range module and block scan. I'm going to test some more this afternoon as a standalone mod to rule out my end

**Comment by fnuecke** [comment]
I'm afraid I don't have time to support older MC versions.  If this is still happening on the latest version (without additional shader mods or the like), please open a new ticket with new logs, thanks.

**Comment by fnuecke** [comment]
I'm afraid I don't have time to support older MC versions.  If this is still happening on the latest version (without additional shader mods or the like), please open a new ticket with new logs, thanks.

**Comment by fnuecke** [comment]
I'm afraid I don't have time to support older MC versions.  If this is still happening on the latest version (without additional shader mods or the like), please open a new ticket with new logs, thanks.
