### ISSUE TITLE
Crash upon game initialization

### ISSUE THREAD

**Issue by NerjalNosk** [MightyPirates/Scannable#108]
I don't know why, it might be linked to one of the other mods, although I haven't tried testing them together yet.
Here be the crashlog

```log
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: *I'd rather hide that*
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'scannable'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: field_15517
	at li.cil.scannable.client.ClientConfig.lambda$static$1(ClientConfig.java:63)
	at net.minecraft.class_156.method_654(class_156.java:458)
	at li.cil.scannable.client.ClientConfig.<clinit>(ClientConfig.java:62)
	at li.cil.scannable.util.ConfigManager.lambda$add$6(ConfigManager.java:130)
	at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:580)
	at li.cil.scannable.util.ConfigManager.add(ConfigManager.java:129)
	at li.cil.scannable.common.Scannable.onInitialize(Scannable.java:15)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) *I'd rather hide that*
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 467750352 bytes (446 MiB) / 1308622848 bytes (1248 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: *I'd rather hide that*
	Identifier: Intel64 *I'd rather hide that*
	Microarchitecture: whiskey Lake
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x9b41
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5905.98
	Virtual memory used (MB): 5679.05
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 726.50
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adb: Accessible Dev Blocks ${version}
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancements-enlarger: Advancements Enlarger 0.2.4
		ae2: Applied Energistics 2 10.0.0
		ae2wtlib: AE2WTLib 10.0.1-release
		alloy_forgery: Alloy Forgery 2.0.9+1.18
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.1.44
		armorhotswap: ArmorHotswap 1.7
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.4
		awesomedungeon: Awesome Dungeon 2.0.8
		awesomedungeonend: Awesome Dungeon Edition end 1.0.0
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.1
		bclib: BCLib 1.3.5
		betterdroppeditems: Better Dropped Items 1.3.1-21w37a
		betterdungeons: YUNG's Better Dungeons 1.18-1.0
		bettermounthud: Better Mount HUD 1.1.2
		betternether: Better Nether 6.0.11
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		blockus: Blockus 2.3.10+1.18.1
		bookshelf: Bookshelf 12.0.23
		boostedbrightness: Boosted Brightness 2.1.0
		boringbackgrounds: Boring Backgrounds 3.0.6+1.18.rc3
		bountiful: Bountiful 2.0.1
		bsvsb: Better Sodium Video Settings Button 2.0.5
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		capes: Capes 1.2.2+1.18
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		carpet: Carpet Mod 1.4.57
		carpet-extra: Carpet Extra 1.4.56
		cavetweaks: Cave Tweaks 1.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		cleanview: CleanView 1.18-v1-fabric
		cleardespawn: Clear Despawn 1.1.5
		clickadv: Clickable Advancements Mod 2.5
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		clumps: Clumps 8.0.0+5
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		continuity: Continuity 1.1.0+1.18
		controlling: Controlling For Fabric 9.0.4
		cpas: cpas 3.0.0
		cpas-api: cpas-api 3.0.0
		cpas-runtime: cpas-runtime 3.0.0
		cpas-trinkets: cpas-trinkets 3.0.0
		craftpresence: CraftPresence 1.8.8
		crowdin-translate: CrowdinTranslate 1.4+1.18
		custom-fog: Custom Fog 2.1.0
		customfov: Custom FoV 1.4.1-1.18.1
		customportalapi: Custom Portal Api 0.0.1-beta49-1.18
		customsplashscreen: Custom Splash Screen 1.2.0
		customstars: Custom Stars 0.7+1.18
		darkutils: DarkUtilities 9.0.2
		dawn: Dawn API 3.2.0
		decorative_blocks: Decorative Blocks 2.0.4
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dragonloot: DragonLoot 1.0.10
		drinkbeer: Drink Beer 3.0.2
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dungeons_arise: When Dungeons Arise 2.1.49d-fabric
		durabilityviewer: Giselbaers Durability Viewer 1.18-fabric0.43.1-1.10.2
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		ecologics: Ecologics 1.3.0
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchdesc: EnchantmentDescriptions 9.0.13
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabric_hider: Fabric Hider 1.0.0
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		forgeconfigapiport: Forge Config API Port 3.1.1
		gatewayer: Gatewayer mc1.18.1-v1.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.33
		graveyard: The Graveyard 1.6
		guardvillagers: Guard Villagers Fabric 1.18.1-1.0.11
		gud_recipe_confidence: Recipe Confidence 1.0.2
		healthoverlay: Health Overlay 6.0.1
		incubus_core: Incubus Core 1.6.6+1.18.1
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.5.1-1.18.1
		inventoryprofilesnext: Inventory Profiles Next 1.3.5
		itemscroller: Item Scroller 0.16.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.1-1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libraryferret: Library Ferret 1.0.3
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.8
		loading-timer: Loading Timer 1.5+21w42a
		malilib: MaLiLib 0.11.7
		megane: megane 7.1.3
		megane-api: megane-api 7.0.0
		megane-applied-energistics-2: megane-applied-energistics-2 7.0.1
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-reborn-energy: megane-reborn-energy 7.0.0
		megane-runtime: megane-runtime 7.1.3
		megane-vanilla: megane-vanilla 7.0.0
		milk: Milk Lib 0.1.5
		milk_plus: Milk+ 2.0.1
		minecraft: Minecraft 1.18.1
		minihud: MiniHUD 0.21.3
		modid: Creatures Of The Snow 1.0.0
		modmenu: Mod Menu 3.0.1
		moreachievements: MoreAchievements 1.0.7
		moretags: More Tags 2.0.2
		mostructures: Mo' Structures 1.3.1+1.18.1
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		notenoughanimations: NotEnoughAnimations 1.4.0
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		ordinarytweaks: SomeOrdinaryTweaks 1.1.0
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		oro_config: OroArmor Config 2.1.0
		owo: oωo 0.5.2+1.18
		particlerain: Particle Rain 2.0.0
		patchouli: Patchouli 1.18.1-65-FABRIC
		petowner: Pet Owner 1.8.2-1.18-pre4+
		phosphor: Phosphor 0.8.1
		pride: Pride Lib 1.1.0+1.17
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.3.432
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		satin: Satin 1.7.2
		scannable: Scannable 1.7.6
		sheepconsistency: Sheep Consistency 1.0.3
		simple_shelves: Simple Shelves 1.0.4
		skinswapper: Skin Swapper 3.0.0
		smoothboot: Smooth Boot 1.18-1.7.0
		smootherbedrock: Smoother Bedrock 1.0.4
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.4.0-alpha6+build.14
		spectrum: Spectrum 1.2.17-1.18.1-midgame17-trinkets-brewing
		spirit: Spirit 1.2.3
		spruceui: SpruceUI 3.3.0+1.17
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 2.2.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_aether: Paradise Lost 1.6.8+1.18.1
		the_bumblezone: The Bumblezone - Fabric 4.3.6+1.18.1
		things: Things 0.2.15+1.18
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		twigs: Twigs 1.1.2
		universal_ores: Universal Ores 1.2.1
		waterdripsound: Drip Sounds 1.18-0.3.0
		waystones: Waystones 2.4.1
		whyamionfire: Why Am I on Fire? 1.1.1
		wthit: wthit 4.5.4
		xaerominimap: Xaero's Minimap 22.2.0.1
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yungsapi: YUNG's API 1.18-Fabric-36
	Launched Version: fabric-loader-0.13.3-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by fnuecke** [comment]
The fabric version is for 1.18.2 not for 1.18.1.
