### ISSUE TITLE
Scannable Mod Incompatible With Fabric API v0.88.1+1.20.1

### ISSUE THREAD

**Issue by Manos654764** [MightyPirates/Scannable#134]
take a look at this:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Scannable' (scannable) 1.7.8+2160e98 with any version that is compatible with:
		 - fabric-api 0.88.1+1.20.1
Unmet dependency listing:
	 - Mod 'Scannable' (scannable) 1.7.8+2160e98 requires version 0.87.0+1.20.1 of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.88.1+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

How To Reproduce:
Have Latest version of Fabric API
Download Scannable mod
Get Error

**Comment by fnuecke** [comment]
Hmm, dependency should have been greater or equal, might have tagged a commit too early or so.
Will make a new release with >= 0.88 soon, adjusted in b77b069bb9da17410bea9ee19e1a6b143f28485d.
