### ISSUE TITLE
[1.11.2] Conflict with newest version of Rustic (0.3)

### ISSUE THREAD

**Issue by jesmores** [MightyPirates/Scannable#14]
Confirmed on test pack with just Rustic and Scannable. World loads, but no chunks are loaded. More details on the issue I opened on Rustic: https://github.com/the-realest-stu/Rustic/issues/10

Scannable 1.3.1.19
Rustic 0.3

Log: https://gist.github.com/jesmores/ae0246c6bb2c4ebf5e191c90308a3bc6

This is probably the more interesting part of the log:
```
java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=axis, clazz=class net.minecraft.util.EnumFacing$Axis, values=[x, z]} to y on block rustic:grape_leaves, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227) ~[atm$a.class:?]
	at rustic.common.blocks.crops.BlockGrapeLeaves.func_180651_a(BlockGrapeLeaves.java:99) ~[BlockGrapeLeaves.class:?]
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.buildOreCache(ScanResultProviderBlock.java:434) ~[ScanResultProviderBlock.class:?]
	at li.cil.scannable.client.scanning.ScanResultProviderBlock.rebuildOreCache(ScanResultProviderBlock.java:88) ~[ScanResultProviderBlock.class:?]
	at li.cil.scannable.common.config.Settings.setServerSettings(Settings.java:232) ~[Settings.class:?]
	at li.cil.scannable.client.network.handler.MessageHandlerConfig.onMessage(MessageHandlerConfig.java:15) ~[MessageHandlerConfig.class:?]
	at li.cil.scannable.client.network.handler.MessageHandlerConfig.onMessage(MessageHandlerConfig.java:11) ~[MessageHandlerConfig.class:?]
```

**Comment by jesmores** [comment]
Rustic just pushed a fix on their end. I will close this once I can confirm the issue is gone on my pack.

**Comment by jesmores** [comment]
Fixed now, closing this.
