### ISSUE TITLE
Scannables identified as crash on "MC Eternal" modpack

### ISSUE THREAD

**Issue by Jwn5k** [MightyPirates/Scannable#71]
I have already opened an issue report with the MC Eternal modpack creator's github, and hopefully you can use the crash report for it here too and maybe make some use of it.
This only happens to this one friend of mine, and nobody else out of the half dozen others I have playing on my hosted server.
His computer is very good and should have no problem. 
He played on the server previously and was suddenly unable to play and keeps crashing now. HE has uninstalled the whole modpack, verified it, multiple times, uninstalled the mod itself and reinstalled it multiple times from the modpack, as well as me sending him my own .jar of the mod and .cfg file and to no avail, still says Scannables is the what may be causing the problem according to the crash screen, I would appreciate it quite a lot if you look into it. Thanks.
![image](https://user-images.githubusercontent.com/63528620/99869920-c6be4300-2b83-11eb-8b49-802e04012819.png)
[crash-2020-10-04_21.13.16-client.txt](https://github.com/MightyPirates/Scannable/files/5577156/crash-2020-10-04_21.13.16-client.txt)

**Comment by Jwn5k** [comment]
It is using Scannables version 1.6.3.24 
Hopefully if there is an issue you can fix with it, if any, send the modpack creator adam98991 a pm to tell him to update the modpack.

**Comment by fnuecke** [comment]
Is that a crash log from such a crash? Since at least the file name is different from the screen shot. If it is, I have no idea how the report screen comes to the conclusion Scannable is involved, this is the trace from the one you posted:
```
java.lang.ArrayIndexOutOfBoundsException: -1
    at electroblob.wizardry.util.WandHelper.getCurrentMaxCooldown(WandHelper.java:355)
    at electroblob.wizardry.client.gui.GuiSpellDisplay.draw(GuiSpellDisplay.java:173)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_825_GuiSpellDisplay_draw_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
    at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:349)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:142)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1421)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Which crashes in `electroblob.wizardry.util.WandHelper.getCurrentMaxCooldown`, which appears to be [this mod](https://github.com/Electroblob77/Wizardry). Though looking at the method in question I don't quite see how it'd crash there.

So yeah, please double-check you posted the right crash log, thanks!

**Comment by Jwn5k** [comment]
I just asked for the most recent crash log at the bottom of the list in the crash logs folder for MC Eternal. 
It looks like the mod in question has something to do with a wand, I have a tool to edit items out of an offline player's inventory, I will try and remove any "wand" items from their inventory just in case that (for some reason???) is what is causing this. But here's the thing, I completely removed all playerdata files from the folder which it resides in, so in that case he would have nothing on him, yet the crash still persisted. I will verify that this IS the most recent crash file, as the screenshot WAS from last month, but the crash report was from just yesterday, and he said it is crashing still because of Scannables. I will reply again to verify that that is the most recent crash log the game has given him.

**Comment by Jwn5k** [comment]
[crash-2020-11-20_22.16.38-client.txt](https://github.com/MightyPirates/Scannable/files/5580369/crash-2020-11-20_22.16.38-client.txt)
This should be the most up to date crash log, check it in case it has any differences. Please let me know if there are any issues that i can correct on my end, if any. (Sorry I took almost 2 days, he was not at his computer for quite a while)

**Comment by fnuecke** [comment]
Thanks for the updated log! The crash should be fixed in the new build/version. Can't promise OptiFine integration still works though.
